### ISSUE TITLE
Transparent Terminal Support

### ISSUE THREAD

**Issue by Christian77777** [navarasu/onedark.nvim#10]
Really liking this vim theme, especially the deep variation.
However, one thing keeping me from using it is that I wish to have a transparent background in my supported terminal.
I was hoping you could implement a vim variable to toggle the appropriate colors to make that happen.
An example would be https://github.com/joshdick/onedark.vim#onedarkextend_highlight

**Comment by navarasu** [comment]
I will add a flag to enable or disable 
```
vim.g.onedark_transparent_background = true
```

**Comment by navarasu** [comment]
Added transparent background support
### To enable transparent background
```vim
let g:onedark_transparent_background = 1 " By default it is 0
colorscheme onedark
```

```lua
vim.g.onedark_transparent_background = true -- By default it is false
require('onedark').setup()
```

**Comment by axieax** [comment]
Hi, just wondering whether it is possible to more finely customise the transparency of the background, e.g. opacity of 0.8.

**Comment by navarasu** [comment]
@axieax Please raise it as new issue. I will add that option
