### ISSUE TITLE
Tips on customizing which-key highlights.

### ISSUE THREAD

**Issue by earlyaugust2** [navarasu/onedark.nvim#101]
Any tips on how I could get which-key to look like so? I mainly want to change the background, which seems transparent while not showing the underlying text. I tried adding `WhichKeyFloat` under highlights but that doesn't seem to work. 

<img width="1428" alt="Screen Shot 2022-08-20 at 11 46 59 PM" src="https://user-images.githubusercontent.com/16395981/185779373-9c993ece-ff57-4842-9f97-9d813d9a643e.png">

**Comment by xeluxee** [comment]
`WhichKeyFloat` is the right highlight group. Please share your onedark setup
If you want to see underlying text you should enable `winblend` in [whichkey setup](https://github.com/folke/which-key.nvim#%EF%B8%8F-configuration)

**Comment by earlyaugust2** [comment]
@xeluxee Thanks for the response. This is what I currently have

```
require("onedark").setup {
            style = "warmer",
            transparent = true,
            highlights = { WhickKeyFloat = { bg = "NONE" } },
          }
```

**Comment by xeluxee** [comment]
If you want to make WhichKey background black set `bg` to some hex code, like `#080211`

**Comment by earlyaugust2** [comment]
@xeluxee I actually want it to be `none` like in the screenshot I shared. I think the problem is the custom highlights aren't working. It looks like someone else is having this problem as well in issue #102 . Have you tried setting the background for `WhichKeyFloat`? Is it working for you?

**Comment by Xemptuous** [comment]
> @xeluxee I actually want it to be `none` like in the screenshot I shared. I think the problem is the custom highlights aren't working. It looks like someone else is having this problem as well in issue #102 . Have you tried setting the background for `WhichKeyFloat`? Is it working for you?

I am able to get WhichKeyFloat color highlight working when I use it. 
Your code you pasted has a typo, not sure if that's why. 

You have: `WhickKeyFloat` 
instead of `WhichKeyFloat`

Looking at the source, if you want no background, you should use `bg = "cfg.transparent"`, which worked for me.

**Comment by xeluxee** [comment]
> I think the problem is the custom highlights aren't working.

Customs highlights work properly, you can check it by editing other common highlight groups

> Have you tried setting the background for WhichKeyFloat? Is it working for you?

It's working for me. As @Xemptuous pointed out, the code you pasted has a typo

**Comment by earlyaugust2** [comment]
@Xemptuous @xeluxee  Fuck it was because of the typo. Thanks for pointing that out! All is good now
