### ISSUE TITLE
Custom Highlights Not Working

### ISSUE THREAD

**Issue by Xemptuous** [navarasu/onedark.nvim#102]
I might be having a complete newbie issue, but I am not able to get custom TS highlights to work when making the changes in my init.lua

Here is what I have for my OneDark section:
```
require('onedark').setup {
     style = 'darker',
     highlights = {
         TSFunction = {fg = '#4fa6ed', bg = '#053963', fmt = 'underline,bold'},
         TSMethod = {fg = '#4fa6ed', bg = '#053963', fmt = 'underline,bold'},
         TSFunctionCall = {fg = '#4fa6ed'},
         TSMethodCall = {fg = '#4fa6ed'}
     }
}
require('onedark').load()
```
Not sure what my current issue is, but no changes that I make here are reflected in any of my code (python). 

I would appreciate any help!

On a side note: is there any TS highlighting for classes?

**Comment by xeluxee** [comment]
If you are using packer run `:PackerCompile` and restart Neovim

**Comment by Xemptuous** [comment]
> 

I am using `vim-plug`, so I don't have `:PackerCompile`. 

I have looked into on-demand lazy loading it, but also unable to get that to work properly.

the `setup {}` is able to implement the chosen style properly, just not the custom highlighting.

**Comment by Xemptuous** [comment]
Solved: incorrect tree-sitter options. Fixed by switching to minimum specs.
