### ISSUE TITLE
lualine.nvim does not render colors properly when using this plugin

### ISSUE THREAD

**Issue by moshiur-raj** [navarasu/onedark.nvim#11]
![image](https://user-images.githubusercontent.com/36466700/126560526-ba8bb3d8-400f-48d2-a830-0032ad54ab63.png)
The colors do not match. I tried joshdick/onedark.vim and it worked fine. I am using neovim 0.5+.

**Comment by navarasu** [comment]
Which colors does not match? I see they have similar colors.

**Comment by moshiur-raj** [comment]
![image](https://user-images.githubusercontent.com/36466700/126612973-46be624e-abdf-48cc-983b-d6093fd87f89.png)
It should be like this. https://github.com/hoob3rt/lualine.nvim/blob/master/THEMES.md

**Comment by moshiur-raj** [comment]
![image](https://user-images.githubusercontent.com/36466700/126614345-9d26869b-bf39-47b7-a648-1c1c6fc99c23.png)
Using joshdick/onedark.vim

**Comment by navarasu** [comment]
Got it. I will update that. Thanks for raising this issue

**Comment by moshiur-raj** [comment]
@navarasu lualine provides the theme onedark by default.  It seems your  extension is overriding it. In that case you just need to remove the lualine theme from your plugin and let lualine load it's own theme.
https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/themes/onedark.lua

**Comment by navarasu** [comment]
Updated lualine as per latest config to fix line number no color issue. Also, updated the lighter bg for the bar
<img width="1440" alt="Screenshot 2021-07-26 at 2 20 41 AM" src="https://user-images.githubusercontent.com/20145075/126913166-55223fdd-34f2-450d-9074-fd2af57e3c60.png">

**Comment by moshiur-raj** [comment]
Thanks.
