### ISSUE TITLE
the color of the environment text verbatim

### ISSUE THREAD

**Issue by oriyia** [navarasu/onedark.nvim#111]
Hi! By default, the verbatim text is colored magenta, but when the treesitter backlight is turned on, the text in the verbatim environment stops being highlighted. I could not find a parameter that could be responsible for this. Expected it to be possible `TSLiteral`. Or is treesitter to blame for this?

**Comment by wangweixuan** [comment]
It seems treesitter doesn't have special rules for `verbatim` environment.
Your can use the following command to open a file and add rules to treesitter:
```
:TSEditQueryUserAfter highlights latex
```
and write
```scm
;; extends
(verbatim_environment) @text.verbatim
```
This adds the highlight group `@text.verbatim`.
Note that you [need Nvim v0.8.0 and latest version of treesitter plugin](https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1279974776), which supports new highlight group names.
Then you can specify the color for this group in plugin config:
```lua
require('onedark').setup {
    highlights = {
        ['@text.verbatim'] = {fg = '$purple'}
    }
}
```

**Comment by oriyia** [comment]
Thank you very much! I tried to implement a similar one, but it did not work in any way.
