### ISSUE TITLE
Incorrect background color when using tmux

### ISSUE THREAD

**Issue by nnazo** [navarasu/onedark.nvim#112]
Hey there! I was hoping to use this theme with LunarVim but I'm having issues with it not displaying the right colors. This issue isn't happening for me with other themes.

Here's all the different styles for reference:
![image](https://user-images.githubusercontent.com/6753860/196088736-6e212cc7-4478-4fb2-bb04-1d6b8ec96f81.png)
![image](https://user-images.githubusercontent.com/6753860/196088773-dc4d348b-1eda-4531-b010-195876b2c6cd.png)
![image](https://user-images.githubusercontent.com/6753860/196088808-bec37bbe-50ed-49f4-8052-9ec5d93a60b8.png)
![image](https://user-images.githubusercontent.com/6753860/196088860-941bd38e-0def-4df8-bc44-3ca077da83f7.png)
![image](https://user-images.githubusercontent.com/6753860/196088882-b0b2a589-5311-4afb-aa5f-6655edf62ed2.png)
![image](https://user-images.githubusercontent.com/6753860/196088910-7edb9eea-0279-4810-8c25-674f762f7b6e.png)

Any idea what the issue is?

**Comment by nnazo** [comment]
Realized this was an issue with tmux messing with the colors, not an issue with the theme. For any future onlookers that stumble across this, add this to your `.tmux.conf`:
```
set-default colorset-option -ga terminal-overrides ",xterm-256color:Tc"
```

**Comment by dagadbm** [comment]
this is what made it possible for me to migrate to WezTerm thanks for this issue my friend!

**Comment by reilg** [comment]
> Realized this was an issue with tmux messing with the colors, not an issue with the theme. For any future onlookers that stumble across this, add this to your `.tmux.conf`:
> 
> ```
> set-option -ga terminal-overrides ",xterm-256color:Tc"
> ```

Thanks for this solution. I've been pulling my hair for a good hour over this.
But for my own edification, could please tell me what happened here?
