### ISSUE TITLE
Getting repeated error 'W18: Invalid character in group name'

### ISSUE THREAD

**Issue by tamausb** [navarasu/onedark.nvim#113]
This seems to be coming from the additions of 
`["@***"] = colors.*,`
in the file `lua/onedark/highlights.lua`

If these lines are removed then the error's go away.

**Comment by dave-kennedy** [comment]
Thanks for the quick turnaround!

**Comment by navarasu** [comment]
Please upgrade to neovim 0.8 version and update https://github.com/nvim-treesitter/nvim-treesitter
