### ISSUE TITLE
Invalid character in group name

### ISSUE THREAD

**Issue by sleaper** [navarasu/onedark.nvim#119]
Hi,
After I updated all plugins I'm getting this error at the start of neovim:
![image](https://user-images.githubusercontent.com/19505081/200078294-052ec674-b3c4-493d-8f58-df2c836713c1.png)

I use nvim version 0.8
I load colorscheme like this:

```
local colorscheme = 'onedark'
local status_ok, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
if not status_ok then
	vim.notify("colorscheme " .. colorscheme .. " not found!")
	return
end
```

Any idea where is the problem?

**Comment by navarasu** [comment]
Update [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) plug-in as well

**Comment by sleaper** [comment]
Actually, I got this error after I updated treesitter.

**Comment by navarasu** [comment]
Please make sure you have latest nvim version and nvim treesitter plugin. There is magic other than that

**Comment by cmattinson** [comment]
@sleaper Not sure if you're still having this issue, but I had to install the latest [nightly release](https://github.com/neovim/neovim/releases/tag/nightly) to fix this. After updating my plugins I was also having this issue on v0.8.0.

**Comment by sleaper** [comment]
> Please make sure you have latest nvim version and nvim treesitter plugin. There is no magic other than that

Yes that was it, I had some strange version of neovim. I updated to neovim 0.8.0 and everything works perfectly fine! Thank you!
