### ISSUE TITLE
Telescope text not display properly

### ISSUE THREAD

**Issue by c4dr01d** [navarasu/onedark.nvim#13]
I just configured telescope, when I hit shortcut to launch telescope file_files, I got this:
![屏幕截图 2021-08-11 101418](https://user-images.githubusercontent.com/50952350/128959394-39833397-49fd-4145-afed-d26bb05d71c2.png)
It's my configuration wrong?

**Comment by navarasu** [comment]
Please log this issue to https://github.com/nvim-telescope/telescope.nvim and check with that team
