### ISSUE TITLE
Typo in highlights.lua

### ISSUE THREAD

**Issue by jkorb** [navarasu/onedark.nvim#134]
The highlights contain the following lines:

https://github.com/navarasu/onedark.nvim/blob/89dde4963ad198c9b6144dee3d5e8bcbb7559ddc/lua/onedark/highlights.lua#L185-L186

These captures should be:

```lua
        ["@text.environment"] = colors.Fg,
        ["@text.environment.name"] = colors.Fg,
```

That is, "enviroment" [sic] in the published code should be "environment".

The mispelled captures cause subtle problems, which I was banging my head against the wall about until I figured this out.

I'd be happy to create a quick PR to fix this, if this helps!

Anyways, thanks for the fantastic theme :)

**Comment by navarasu** [comment]
Thank you for finding this. Even I missed this while review. I will fix it right away
