### ISSUE TITLE
diff does not highlight with treesitter

### ISSUE THREAD

**Issue by classabbyamp** [navarasu/onedark.nvim#137]
in a recent version, the treesitter highlight groups for diffs seem to have changed to `@text.diff.add` and `@text.diff.delete` and diff highlighting no longer works with this theme. I tried fixing this myself in highlights.lua but I couldn't get it to work.

**Comment by Sciencentistguy** [comment]
The issue is as of this change https://github.com/nvim-treesitter/nvim-treesitter/pull/3656 in nvim-treesitter. pinning a version before that works around this problem

**Comment by classabbyamp** [comment]
thanks for the workaround

**Comment by samhed** [comment]
The workaround resolved the issue for me as well:
```
< Plug 'nvim-treesitter/nvim-treesitter', { 'commit': '4cccb6f494eb255b32a290d37c35ca12584c74d0', 'do': ':TSUpdate'}
```

Is there a proper fix in the works? Can I help?

**Comment by classabbyamp** [comment]
can you test out #142 ?

**Comment by samhed** [comment]
I removed the workaround and applied the change from #142, it works well. Thanks a lot!
