### ISSUE TITLE
Disabling italics does not apply to all languages

### ISSUE THREAD

**Issue by dcordb** [navarasu/onedark.nvim#14]
Thanks for this project.

I want to disable italics but it is not working. Steps to repro:

1. Create a minimal config `init.vim`:

```
call plug#begin('~/.config/nvim/plugged') " change here to your plugins folder
    Plug 'navarasu/onedark.nvim'
call plug#end()

" This is a comment
" Note how italic font appears even though I have disable it

let g:onedark_italic_comment = 0
colorscheme onedark
```
2. Execute `nvim -u init.vim init.vim` (open init.vim with minimal config)
3. You should see the comments in italic

This is happening with Cascadia Code font (https://github.com/microsoft/cascadia-code).

Note that for JetBrains Mono for example this does not happen.

**Comment by navarasu** [comment]
Looks vim config has issue. I will fix it
But lua config is working fine. You can check that.

```lua

vim.g.onedark_italic_comment = false   require('onedark').setup()

```

**Comment by xeluxee** [comment]
If you are using vimscript to set boolean values that will be read by lua you should use `v:false` or `v:true` instead of `0` or `1`.

``` vim
let g:onedark_italic_comment = v:false
colorscheme onedark
```

**Comment by navarasu** [comment]
Docs is updated by @xeluxee. So closing this issu
