### ISSUE TITLE
Doesn't look very good on Rust with semantic tokens from NeoVim 0.9

### ISSUE THREAD

**Issue by Ciel-MC** [navarasu/onedark.nvim#140]
1. Traits' color is "Identifier" and ends up not looking very good
![image](https://user-images.githubusercontent.com/47144701/217021106-8c5996ad-b5ec-47b5-a60f-d8ca99ac66a9.png)
2. enum members, and attribute helpers, uses the same color and look like a blob
![image](https://user-images.githubusercontent.com/47144701/217022501-36d3d9bd-4c5d-4158-9cd1-70c452e0a223.png)
Comparison: With semantic tokens off:
![image](https://user-images.githubusercontent.com/47144701/217022609-f29f17f3-7b70-40c7-9c11-d899bb645979.png)

**Comment by IndianBoy42** [comment]
The second problem seems to be that @lsp.type.enumMember is linked to Constant by default by neovim, this plus rust-analyzer probably encompasses too much within that token 

I added this 
```
vim.api.nvim_create_autocmd("ColorScheme", {
  callback = function()
    vim.api.nvim_set_hl(0, "@lsp.type.enumMember.rust", { link = "Type" })
  end,
})
```

You could also just clear the link by passing an empty `{}` or connect it to something else
