### ISSUE TITLE
Indent-blankline plugin no longer working

### ISSUE THREAD

**Issue by MahboobMMonza** [navarasu/onedark.nvim#144]
With one of the recent PRs for this repo, support for indent blankline stopped working for some reason. I used to have "show_current_context" section enabled, but now that does not work and no context is shown. When I disable this plugin, indent-blankline works fine. What is the reason for this?

**Comment by MahboobMMonza** [comment]
Update: After setting the char_highlight_list colours, all other characters are highlighted, but current context is greyed out. I was expecting the opposite effect.

**Comment by comiluv** [comment]
Use setup something like this:
```lua
require("onedark").setup({
  highlights = {
	  IndentBlanklineContextChar = { fg = "$light_grey", fmt = "nocombine" },
	  IndentBlanklineContextStart = { sp = "$light_grey", fmt = "nocombine,underline" },
  }
})
```

**Comment by MahboobMMonza** [comment]
Thanks!
