### ISSUE TITLE
Change the color of the folder icon

### ISSUE THREAD

**Issue by oriyia** [navarasu/onedark.nvim#147]
I can't change the color of the directory icon. I didn't find a parameter in the file `highlights.lua` that would be responsible for this.

Previously , it was possible to implement this through:
```
api.nvim_set_hl(0, "NvimTreeFolderIcon", {
    fg = "#eeeeee",
})
```
But now that doesn't work either.

**Comment by xeluxee** [comment]
You should put custom highlights in [setup](https://github.com/navarasu/onedark.nvim#customization)

**Comment by oriyia** [comment]
It turned out to do this:
```
highlights = {     
    NvimTreeFolderIcon = {
        fg = "#eeeeee"
    },
}
```
This parameter should probably be added to the `highlights.lua` file?
