### ISSUE TITLE
Installation issue: module 'onedarkpro.config' not found

### ISSUE THREAD

**Issue by alexnivanov** [navarasu/onedark.nvim#151]
Greetings!

I'm new to neovim and making a fresh setup. I'm on MacOS Ventura 13.2 and installed latest nvim 0.8.3 using Homebrew.

I've installed VimPlug and added the plugin as suggested:
`Plug 'navarasu/onedark.nvim'`

This is currently the only plugin installed!

And when I enable `colorscheme onedark` I'm getting the following error on nvim start:
```
Error detected while processing /Users/alex/.config/nvim/init.vim[44]../Users/alex/.local/share/nvim/site/pack/packer/opt/onedarkpro.nvim/colors/onedark.vim:
line    4:
E5108: Error executing lua [string ":lua"]:1: module 'onedarkpro.config' not found:
        no field package.preload['onedarkpro.config']
        no file './onedarkpro/config.lua'
        no file '/opt/homebrew/share/luajit-2.1.0-beta3/onedarkpro/config.lua'
        no file '/usr/local/share/lua/5.1/onedarkpro/config.lua'
        no file '/usr/local/share/lua/5.1/onedarkpro/config/init.lua'
        no file '/opt/homebrew/share/lua/5.1/onedarkpro/config.lua'
        no file '/opt/homebrew/share/lua/5.1/onedarkpro/config/init.lua'
        no file './onedarkpro/config.so'
        no file '/usr/local/lib/lua/5.1/onedarkpro/config.so'
        no file '/opt/homebrew/lib/lua/5.1/onedarkpro/config.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './onedarkpro.so'
        no file '/usr/local/lib/lua/5.1/onedarkpro.so'
        no file '/opt/homebrew/lib/lua/5.1/onedarkpro.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

**Comment by xeluxee** [comment]
I think you've installed this OneDark along with https://github.com/olimorris/onedarkpro.nvim
They conflict because of this [file](https://github.com/olimorris/onedarkpro.nvim/blob/main/colors/onedark.vim), so you should uninstall one of the two.

**Comment by alexnivanov** [comment]
@xeluxee thanks for the info! Can you please hint how to remove the other? Sorry I'm vim noob 😅

**Comment by xeluxee** [comment]
If you installed it manually you should remove it from rtp. If you used a package manager you should remove the line with plugin name and then launch the command to clean packages (`:PlugClean`, `:PackerClean`, `:Lazy clean`, etc.)

**Comment by alexnivanov** [comment]
Hmm I've tried a bunch of things, and some of them actually resolved the issue, thanks!
