### ISSUE TITLE
All variables and object properties turned red

### ISSUE THREAD

**Issue by BaGreal2** [navarasu/onedark.nvim#161]
After interacting with a file all the variables and object properties turn red. Before interacting the highlight is normal. Changing fg color manually doesn't help
![Screenshot 2023-04-18 at 23 39 50](https://user-images.githubusercontent.com/48404129/232899901-fcbd5795-4a1c-4e31-9239-868e1dcace6e.png)
![Screenshot 2023-04-18 at 23 40 01](https://user-images.githubusercontent.com/48404129/232899936-15224563-6bce-42e1-a7f0-b44d9544bc9c.png)

**Comment by tudorjnu** [comment]
I have the same problem. How did you fix it? :)
