### ISSUE TITLE
Colores are faded

### ISSUE THREAD

**Issue by danisztls** [navarasu/onedark.nvim#164]
Issue: Colors are faded and doesn't look like in the screenshot

Env: Arch Linux + Gnome Shell + Neovim 0.9

![Screenshot from 2023-05-05 17-25-26](https://user-images.githubusercontent.com/13279154/236562152-8b4aaf0a-f821-4c78-bd4c-e2a469a5fa21.png)

**Comment by navarasu** [comment]
Which style are you using dark or darker?

**Comment by danisztls** [comment]
> Which style are you using dark or darker? 

Dark.

> Also which font are you using?

Hack Nerd Font Regular.

The font weight is the culprit. I'm using regular and you bold.
