### ISSUE TITLE
Loading onedark clears custom highlight definitions

### ISSUE THREAD

**Issue by NiklasKappel** [navarasu/onedark.nvim#182]
This is my favorite neovim colorscheme, so thank you! However, I have one problem with it.

In my `init.lua`, I define a custom highlight group for superfluous whitespace:
```
vim.cmd("highlight BadWhitespace ctermbg=red guibg=red")
vim.api.nvim_create_autocmd({ "VimEnter", "WinEnter" }, { command = [[match BadWhitespace /\s\+$/]] })
```

With onedark installed, but not loaded, the highlight works. Whitespace at the end of lines is marked red and `:hi BadWhitespace` outputs `BadWhitespace  xxx ctermbg=9 guibg=Red`. After using `:colors onedark` however, the highlighting disappears and `:hi BadWhitespace` outputs `BadWhitespace  xxx cleared`.

Other colorschemes do not exhibit this behavior of clearing user defined highlights.

**Comment by NiklasKappel** [comment]
Nevermind, this seems to be a neovim issue.

**Comment by yogeshlonkar** [comment]
This was a problem for me as well. I use Lazy.nvim and couldn't get onedark.nvim to load before everything else.

I endup writting build patch for lazy entry

```lua
return {
  'navarasu/onedark.nvim',
  lazy = false,
  priority = 1000,
  build = [[cat <<EOF | git apply -
diff --git a/lua/onedark/init.lua b/lua/onedark/init.lua
index 05d0998..f97684c 100644
--- a/lua/onedark/init.lua
+++ b/lua/onedark/init.lua
@@ -14,7 +14,6 @@ end

 ---Apply the colorscheme (same as ':colorscheme onedark')
 function M.colorscheme()
-    vim.cmd("hi clear")
     if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
     vim.o.termguicolors = true
     vim.g.colors_name = "onedark"
EOF

  ]],
  init = function()
    vim.cmd([[colorscheme onedark]])
  end
}
```
