### ISSUE TITLE
transparency not consistent

### ISSUE THREAD

**Issue by aserowy** [navarasu/onedark.nvim#19]
heho,

at first: nice one! and thx for this theme!

I love transparency. Thus, enabling it on all themes i use. On your theme sidebars and hop are not transparent. My settings are <https://github.com/aserowy/NeoCode/blob/main/lua/theming/plugin_onedark.lua>. Right now, i get the following look:

![image](https://user-images.githubusercontent.com/8199164/133877508-c383669d-6b1d-4ac4-911b-e0580c617d61.png)

Kind regards

**Comment by navarasu** [comment]
Sure.I will fix this

**Comment by navarasu** [comment]
This issue is fixed. Also improved highlight colors for HOP to support transparent bg. Sorry for the delay in fixing this issue.
