### ISSUE TITLE
`Typedef` link to purple same as `Keyword`

### ISSUE THREAD

**Issue by aMOPel** [navarasu/onedark.nvim#192]
Thank you for your work!

In nvim-treesitter `@type.definition` is usually used for the identifier of a type definition not the keyword.

See https://github.com/nvim-treesitter/nvim-treesitter/issues/5544

Consider an example in golang with the current highlight groups:
```go
type test int
```
`type` and `test` will be purple here.

I looked up how tokyonight handles this:

https://github.com/search?q=repo%3Afolke%2Ftokyonight.nvim%20typedef&type=code

No defining `Typedef` whatsoever.
And indeed `@type.definition` will be redirected to the `Type` highlight group, if the [line](https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/highlights.lua#L114) is deleted.

**Comment by navarasu** [comment]
Now Typedef  is changed to Yellow
