### ISSUE TITLE
Error while calling lua chunk

### ISSUE THREAD

**Issue by TdfGomes** [navarasu/onedark.nvim#2]
Hi there 👋 !
Not sure if it's related with the theme but I have the following error after _source_ my config: 
`E5105: Error while calling lua chunk: ...s/.config/nvim/plugged/onedark.nvim/lua/onedark/init.lua:2: attempt to index field 'g' (a nil value)`

My only plugin is `ondark.vim`:
```
call plug#begin('~/.config/nvim/plugged')
Plug 'navarasu/onedark.nvim'
call plug#end()
```
Thanks in advance if you think this is related

**Comment by navarasu** [comment]
Thanks, TdsGomes for raising this issue. Are u using it with Neovim 0.5 version?

**Comment by TdfGomes** [comment]
No. I am using 
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta
```

**Comment by navarasu** [comment]
Yes. This plugin mainly prepared for Neovim >= 0.5. Neovim >= 0.5 comes with Lua and tree-sitter support. This brings better syntax highlighting and performance.

**Comment by TdfGomes** [comment]
Will try to update neovim and will came back to you.

**Comment by navarasu** [comment]
Also, You need to add [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) plugin to enjoy the tree-sitter syntax. Add tree-sitter syntax
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'} 
Plug 'navarasu/onedark.nvim'
call plug#end()

lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,
  },
}
EOF
```

**Comment by TdfGomes** [comment]
Thanks @navarasu !
It worked!
Awesome job with this project!
Best luck with it!
