### ISSUE TITLE
Recent update to nvim-treesitter breaks markdown highlights

### ISSUE THREAD

**Issue by anhnamtran** [navarasu/onedark.nvim#201]
There is a [recent commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0) that has broken markdown highlighting (and likely others) due to nvim-treesitter deciding to change a lot of their queries to use standard tree-sitter queries.

The changes in question:
* tree-sitter "standard capture names"
  (https://github.com/tree-sitter/tree-sitter/blob/3f44b896852eb7daaa6df4fb778c9bb52c70c815/highlight/src/lib.rs#L20-L72):

  - `@parameter` -> `@variable.parameter`
  - `@field` -> `@variable.member`
  - `@namespace` -> `@module`
  - `@float` -> `@number.float`
  - `@symbol` -> `@string.special.symbol`
  - `@string.regex` -> `@string.regexp`
  - `@text.*` -> `@markup.*` (`strong`, `italic`, `link`, `strikethrough`; with exceptions; see below)
  - `@text.title` -> `@markup.heading`
  - `@text.literal` -> `@markup.raw`
  - `@text.reference` -> `@markup.link`
  - `@text.uri` -> `@markup.link.url` (in markup links)
  - `@string.special` -> `@markup.link.label` (non-url links)
  - `@punctuation.special` -> `@markup.list` (markdown lists only; move subitems from `@text.todo`)

* Helix captures
  (https://docs.helix-editor.com/master/themes.html#syntax-highlighting):

  - `@method` -> `@function.method`
  - `@method.call` -> `@function.method.call`
  - `@text.{todo,warning,note,danger}` -> `@comment.{error,warning,hint,info,todo}`
  - `@text.diff.{add,delete,}` -> `@diff.{plus,minus,delta}`
  - `@text.uri` -> `@string.special.url` (outside markup)
  - `@preproc` -> `@keyword.directive`
  - `@define` -> `@keyword.directive`(`.define`?)
  - `@storageclass` -> `@keyword.storage`
  - `@conditional` -> `@keyword.conditional`
  - `@debug` -> `@keyword.debug`
  - `@exception` -> `@keyword.exception`
  - `@include` -> `@keyword.import`
  - `@repeat` -> `@keyword.repeat`

The breakage is due to onedark.nvim not having some of the captures defined.

Some screenshots of running `TSHighlighCaptureUnderCursor` on a header before and after the nvim-treesitter change
![image](https://github.com/navarasu/onedark.nvim/assets/12238924/702f3d24-bc15-4862-a5cb-b75d5907c88e)
 
![image](https://github.com/navarasu/onedark.nvim/assets/12238924/63941d57-143e-4924-81f6-4213028794ea)

**Comment by onns** [comment]
👀
