### ISSUE TITLE
Missing Highlighting in TS, Vue, and lua files

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [navarasu/onedark.nvim#202]
After the latest TreeSitter update highlight groups for Lua and Typescript in typescript and vue files are no longer being highlighted by TreeSitter

**Comment by navarasu** [comment]
@GR3YH4TT3R93 Please take an update and see if you still have this issue.

**Comment by GR3YH4TT3R93** [comment]
That fixed it! Thanks for the great work!
