### ISSUE TITLE
Highlight group 'NotifyBackground' has no background highlight.

### ISSUE THREAD

**Issue by gilbertfrancois** [navarasu/onedark.nvim#207]
I use lazyvim with onedark colorscheme, with **warmer** theme and **transparent** background. When I start neovim, I see the following warning message:

```
2024-02-04T21:11:57 nvim-notify [!] WARN Highlight group 'NotifyBackground' has no background highlight
Please provide an RGB hex value or highlight group with a background value for 'background_colour' option.
This is the colour that will be used for 100% transparency.
```lua
require("notify").setup({
  background_colour = "#000000",
})

Defaulting to #000000
```

[rcarriga/nvim-notify](https://github.com/rcarriga/nvim-notify) has the **NotifyBackground** linked to **Normal**:
```
lua/notify/config/highlights.lua:    hi default link NotifyBackground Normal
```

**Normal** in _onedark_ has this choice between color bg0 or transparent:
```
lua/onedark/highlights.lua:    Normal = {fg = c.fg, bg = cfg.transparent and c.none or c.bg0},
```

Maybe that gives the above mentioned warning, but I don't know if a fix is possible.

**Comment by miloshadzic86** [comment]
I was doing the same as you and I made the error go away by adding this code
```lua
  {
    "rcarriga/nvim-notify",
    config = function()
      require("notify").setup({
        background_colour = "#000000",
      })
    end,
  },
```

**Comment by gilbertfrancois** [comment]
That solved my case. Thank you @miloshadzic86. I'll close the issue.
