### ISSUE TITLE
Colors are not the same as shown in screenshot

### ISSUE THREAD

**Issue by Pismice** [navarasu/onedark.nvim#209]
The title says it all, for exemple here I am trying to use the "Deep" theme, but as you can see of my screenshot colors aint exactly the same, why ? (you can see that especially with the background color)

https://imgur.com/a/UOac6KG

I hope i didnt forget something stupid, but I read the whole doc and didnt find anything like that :(

In my init.lua
`require('onedark').setup {
  style = 'deep'
}
require('onedark').load()`

**Comment by navarasumuthu-ms** [comment]
It works for me. Ensure you have included right one dark package `navarasu/onedark.nvim` and no other onedark package

![image](https://github.com/navarasu/onedark.nvim/assets/116887205/5d6fa9a4-1e99-433c-a7f8-1fbdaea461f0)

**Comment by navarasu** [comment]
It works for me. Ensure you have included right one dark package `navarasu/onedark.nvim` and no other onedark package

![image](https://github.com/navarasu/onedark.nvim/assets/116887205/5d6fa9a4-1e99-433c-a7f8-1fbdaea461f0)

**Comment by Pismice** [comment]
I did, might that maybe not be related to your plugin but my terminal ? (missing bright colors or something)

**Comment by gvnadir** [comment]
In my case the problem was Tmux. Fixed by adding this on my `.tmux.conf` file:

```
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"
```
