### ISSUE TITLE
setting "light" style in setup doesn't do anything

### ISSUE THREAD

**Issue by gnoLLex** [navarasu/onedark.nvim#214]
Fiddled around a bit with setting the colorscheme according to the systems preferred appearance and couldn't figure out why it wouldn't change the scheme properly without setting the background. In [#36 comment](https://github.com/navarasu/onedark.nvim/issues/34#issuecomment-1008006116) they set background **and** style of the plugin, but style is totally ignored. In `lua/onedark/init.lua:21-25` the style is set to `dark` when the style in the config is `light`.

```lua
if vim.o.background == 'light' then
    M.set_options('style', 'light')
elseif vim.g.onedark_config.style == 'light' then
    M.set_options('style', 'dark')
end
```

Is this intended?

**Comment by ctffarley** [comment]
I am also experiencing this behavior, and @gnoLLex 's fork fixes this behavior for me.

**Comment by navarasu** [comment]
@ctffarley @gnoLLex  This has been resolved. Please check now
