### ISSUE TITLE
Correct way to enable the theme in Lua

### ISSUE THREAD

**Issue by mbenford** [navarasu/onedark.nvim#22]
I'm calling `require'onedark'.setup()` to enable the colorscheme, as said in the docs, but I'm experiencing some broken highlights and missing colors. That doesn't happen when I call `colorscheme onedark` instead. Am I doing something wrong?

FWIW, I use Packer as my plugin manager:

`init.lua`
```lua
require'packer'.startup(function(use)
...
  use {'navarasu/onedark.nvim', config = 'require"plugins/onedark"'}
})
```
`plugins/onedark.lua`
```lua
local g = vim.g
g.onedark_style = 'dark'
g.onedark_disable_toggle_style = 1
g.onedark_italic_comment = false
g.onedark_darker_diagnostics = false
require'onedark'.setup()
```

**Comment by xeluxee** [comment]
Sorry I've misunderstood your config :sweat_smile: 
Maybe you should move `require'onedark'.setup()` command outside the config function, after the plugin is loaded

**Comment by mbenford** [comment]
@xeluxee I might be wrong, but I think the correct way to run some code _after_ a plugin is loaded is by using the `config` function.  Otherwise the code might run before the plugin is available since Packer might lazy load things.

**Comment by navarasu** [comment]
@mbenford Now this plugin updated with new lua setup option. Take an update and check with new config

**Comment by mbenford** [comment]
@navarasu I updated my configuration the second I saw the commit. 😀
