### ISSUE TITLE
Support for bold text (such as for function names)

### ISSUE THREAD

**Issue by mmirus** [navarasu/onedark.nvim#23]
Hi there! Thank you so much for this theme!

I was wondering, would it be possible to add support for bold text? For example, to have method names in bold.

Thanks again!

Here's an example from a one dark theme for VS Code:

![image](https://user-images.githubusercontent.com/524994/136471621-55466894-7efa-44b3-ac20-f7b31705c701.png)

**Comment by mmirus** [comment]
That's awesome! Thank you for sharing! I'll have to learn more about that command and what's possible with it. :grin: 

nvim using this theme and that setting:

<img src='https://user-images.githubusercontent.com/524994/136882413-866d9a81-9e80-40f8-b997-9dde6e22f974.png' width='225'>

We can close this if desired, or leave it open if this is something that might still make a good theme option.

**Comment by mikededo** [comment]
One the other hand, do you know if it is possible to disable bold syntax?

**Comment by xeluxee** [comment]
> One the other hand, do you know if it is possible to disable bold syntax?

It'd be cool to have a more granular configuration (similar to `material.nvim`'s one) to let user decide whether to use italics/bold for each highlight or not. I'll make a PR about this if I'm not too busy.

For the moment you can disable bold text from your terminal's settings or disable bold for specific highlights, for example
``` vim
:hi TSKeywordFunction gui=none
```

**Comment by navarasu** [comment]
Please update the plugin. Check custom code_style option. Now we can change style of function, variables, keyword, etc.
