### ISSUE TITLE
Is it possible to customise for a specific language?

### ISSUE THREAD

**Issue by marcfranquesa** [navarasu/onedark.nvim#231]
title

**Comment by Dmitrev** [comment]
Yes and in it's pretty easy, go the file in your chosen language. Then go over to the thing you want to change. I will do it for Booleans in PHP. I put my cursor on the boolean and type `:Inspect` in normal mode which gives me the highlight group under my cursor.

Which is `@boolean.php`

![image](https://github.com/user-attachments/assets/d59811d0-567d-438f-8256-cdc65e82c900)

Now I just go and add this line to my config (must be after you select your theme in your config)

I use lazy.nvim so for me it looks like this:

```lua
    { 
        'navarasu/onedark.nvim',
        lazy = false,
        priority = 1000,
        config = function()
            require('onedark').setup {
                style = 'warmer'
            }
            require('onedark').load()

            -- override booleans
            vim.api.nvim_set_hl(0, "@boolean.php", {fg = "#ff0000"})

        end
    },

```

And sure enough my booleans are red now:
![image](https://github.com/user-attachments/assets/3ab3b636-d005-4c72-80a2-b1b814d4bacf)

**Comment by marcfranquesa** [comment]
thanks Dmitrev!
