### ISSUE TITLE
Overriding terminal cursor color

### ISSUE THREAD

**Issue by felix-clark** [navarasu/onedark.nvim#26]
I'm not sure if this is intended or something specific to my configuration, but both the cursor and search highlight color (i.e. matches on a `/` command) are a pale yellow. They are not exactly the same, but they are close enough to make it quite difficult to identify the cursor location when iterating through search results.

I'm not doing much else that I'd think would interact with the colorscheme, just setting `termguicolors`.

If this is intended, is there a recommended way to adjust the cursor color to something else otherwise consistent with the theme? If it is not normal behavior, how could I go about debugging or fixing this issue?

**Comment by navarasu** [comment]
Closing this issue as it is not related to this colorscheme
