### ISSUE TITLE
autocmd group 'colorscheme' is not triggered when using lua to initialize onedark

### ISSUE THREAD

**Issue by oddlama** [navarasu/onedark.nvim#28]
When using lua to configure onedark with `require("onedark").setup()` as recommended in the README, I noticed that icons from [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons) were never colored, due to their highlight groups being cleared. As far as I know, the icons plugin sets its highlights in an `augroup ColorScheme` callback to be able to reconfigure highlights based on the specific colorscheme (light / dark).

The problem can be fixed by additionally calling `vim.cmd "colorscheme onedark"` immediately after running the setup function. My suspicion is that neovim's internal `colorscheme` command correctly triggers these augroups, while onedarks setup function doesn't. I'm not familiar enough with how colorschemes work internally to suggest a better way of handling things, or whether it is even desirable to completely skip the `colorscheme` command in lua based configurations. I suppose this has to be fixed in onedark's setup function, or at least hinted at in the README.

**Comment by navarasu** [comment]
@oddlama Please update the plugin and check now. This issue is resolved
