### ISSUE TITLE
Feature request: light theme

### ISSUE THREAD

**Issue by gerazov** [navarasu/onedark.nvim#34]
Awesome theme :+1: 

Are there any plans for a light version of the theme, e.g. similar to [rakr/vim-one](https://github.com/rakr/vim-one)?

It would be helpful if one could switch easily on sunny days :sweat_smile:

**Comment by xeluxee** [comment]
Now it's available:
``` lua
vim.o.background = "light"
require('onedark').setup {
	style = 'light',
}
```

**Comment by gerazov** [comment]
Awesome :sunglasses: thanks!
