### ISSUE TITLE
Feature request: override highlight groups

### ISSUE THREAD

**Issue by leoluz** [navarasu/onedark.nvim#35]
First of all, congrats for your theme. It looks really nice with cool treesitter support.

There are a few things I'd like to customize to my taste (eg. Telescope border colors). 
It would be awesome if we could customize highlight groups in the setup function. Something like what onedarkpro does:
https://github.com/olimorris/onedarkpro.nvim#configuring-highlight-groups

**Comment by leoluz** [comment]
This is how I achieved the customization I wanted:

```lua
local colors = require('onedark.colors')
vim.cmd("highlight TelescopeBorder guifg="..colors.grey)
vim.cmd("highlight TelescopePromptBorder guifg="..colors.grey)
vim.cmd("highlight TelescopeResultsBorder guifg="..colors.grey)
vim.cmd("highlight TelescopePreviewBorder guifg="..colors.grey)
```

Its not too bad but having the support to do it directly in the `setup()` function would be better.

**Comment by xeluxee** [comment]
#42 is merged: now you can use `highlights` section in `setup` option
