### ISSUE TITLE
`setup()` refactoring

### ISSUE THREAD

**Issue by xeluxee** [navarasu/onedark.nvim#37]
Hi
I think we should improve `setup` function to let users configure the entire plugin with it, using a config dictionary as argument
However, since the plugin should be configurable trough vimscript too, I think we could do keep a dictionary called `g:onedark_setup`, to be configured before calling the setup function.
All options would then be moved under this dictionary, except for `onedark_style`
Also custom highlights should be added as a setup option, solving issues #35, maybe #33, #23, maybe #17 and #12

@navarasu if you agree with these changes or you have some suggestion let me know, so I'll make a PR

**Comment by navarasu** [comment]
Let's not break existing configs for vim. We can support both legacy and new options.
```vim
" Option 1  - Old one  (Priority 2)
let g:onedark_style = 'darker'
let g:onedark_transparent_background = v:true

" Option 2 (Priority 1)
let g:onedark_option = { 'style':  'darker',  transparent: v:true }
colorscheme onedark
```

```lua
-- Option 3 (Priority 2)
vim.g.onedark_style = 'deep'
vim.g.onedark_italic_comment = false

-- Option 4 (Priority 1)
 require('onedark').setup {
       style = 'darker',
       transparent = true,
       toggle_style_key = '<leader>cs',
       terminal_colors = true, -- True enable the terminal
       hide_ending_tildes = true
       italic = {
         comment = true
       },
       diagnostics = {
           undercurl = true,
           darker_color = true
       }
 }
```

**Comment by xeluxee** [comment]
So you'd like to keep `g:onedark_*` options?
Maybe we could keep them for a month or so, printing warning messages to tell users that these options will be deprecated in favor of the config dictionary (`g:onedark_setup` or `g:onedark_options`) or the lua `setup()` function...

**Comment by navarasu** [comment]
Yes. We can print a deprecated message and support g:onedark_* options for the next 4 months.

**Comment by navarasu** [comment]
@xeluxee As part of this ticket, we can just implement new setup option and support exiting config. No need to solve the issues mentioned in description. We can do that after you doing this migration. 

Meanwhile I will work on transparency based on float value and adding light theme.

**Comment by xeluxee** [comment]
@navarasu I agree
Since in this period I'm busy I won't finish my PR these days, so we'll have to wait a bit before it gets ready to be merged

**Comment by xeluxee** [comment]
Before proceeding, can you tell me if this dictionary looks good or if you have any setting to add?
``` lua
local default_config = {
    toggle_style_keymap = '<leader>cs',
    italics = {
        comments = true,
        keywords = false,
        functions = false,
        strings = false,
        variables = false
    },
    bolds = {
        comments = false,
        keywords = true,
        functions = false,
        strings = false,
        variables = false
    },
    diagnostics = {
        darker = true,        -- darker colors for diagnostics
        undercurl = true,     -- use undercurl for diagnostics
        background = true,    -- use background color for virtual text
    },
    disable = {
        background = false,     -- don't set background (NeoVim then uses your teminal background). If you want transparent background set it to true and make your terminal's background transparent
        term_colors = false,    -- prevent the theme from setting terminal colors
        eob_lines = false       -- hide the end-of-buffer tildes
    },
}
```

**Comment by navarasu** [comment]
@xeluxee Looks fine. But we can avoid two many child parents.  This  [nightfox.nvim](https://github.com/EdenEast/nightfox.nvim) config looks cleaner.

Let's have a config like this,

```lua
local default_config = { 
    -- Main options --
     theme = 'dark', 
     transparent = false,  -- don't set background 
     term_colors = true, -- True enable the terminal
     ending_tilde = false,  show the end-of-buffer tildes
     toggle_theme_key = '<leader>ct',

     -- Changing Styles --
     styles = {
       comment = 'italic',
       keywords = 'NONE',
       functions = 'NONE',
       strings = 'NONE',
       variables = 'NONE'
     },

    -- Custom Highlights --
     colors = {}, -- Override default colors
     highlights = {}, -- Override highlight groups

    -- Plugins Related --
     diagnostics = {
        darker = true, -- darker colors for diagnostic
        undercurl = true,   -- use undercurl for diagnostics
        background = true,    -- use background color for virtual text
     },
 }
```
I have code changes related to the diagnostics background and light theme. Let me push those codes. Take a pull before starting the work.

Also, I am working on improving read me here. [NEW READ ME](https://github.com/navarasu/onedark.nvim/blob/readme_update/README.md). So, I will update the readme for the new config change as well.

**Comment by navarasu** [comment]
I pushed changes related to the diagnostics background and light theme.

**Comment by xeluxee** [comment]
> ```lua
> toggle_theme_key
> ```

Wouldn't `toggle_style_key` be better? Since that keymap doesn't change theme but it changes onedark style

**Comment by navarasu** [comment]
Yeah. You are right. Lets key it as `toggle_style_key`. Also, we can change the `theme` to `default_style`. Then `styles` params have to be changed. So we can call it `format`.
Then the config will be as,
```lua
local default_config = { 
    -- Main options --
     default_style = 'dark', 
     toggle_style_key = '<leader>ct',
     toggle_style_list = ['dark', 'light']
     transparent = false,  -- don't set background 
     term_colors = true, -- True enable the terminal
     ending_tilde = false,  -- show the end-of-buffer tildes

     -- Changing Styles --
     format = {
       comment = 'italic',
       keywords = 'NONE',
       functions = 'NONE',
       strings = 'NONE',
       variables = 'NONE'
     },

    -- Custom Highlights --
     colors = {}, -- Override default colors
     highlights = {}, -- Override highlight groups

    -- Plugins Related --
     diagnostics = {
        darker = true, -- darker colors for diagnostic
        undercurl = true,   -- use undercurl for diagnostics
        background = true,    -- use background color for virtual text
     },
 }
```

**Comment by xeluxee** [comment]
https://neovim.io/doc/user/syntax.html#attr-list

What about changing `format` to `attributes` or `hlattributes`?

**Comment by navarasu** [comment]
Not meaningful. Nvim means it as highlight attributes for cterm. 
What about `text_format`? I remember an old vim plugin with that name like `txtfmt`

**Comment by navarasu** [comment]
Pushed changes related #19. Please take a pull.

**Comment by xeluxee** [comment]
> Not meaningful. Nvim means it as highlight attributes for cterm.

If you scroll down a bit (or `:h highlight-gui`) you'll see that these attributes are the same for cterm and gui




> What about `text_format` or `text_style`?

Good, but what about `code_style`?

**Comment by xeluxee** [comment]
And what about `contrast_windows`?

**Comment by navarasu** [comment]
That we can implement pluginwize later and I have other bigger idea. Planning to add multiple styles for lualine, nvimtree etc.

First we can implement exiting configs and bring in this new setup concept. Then we can add necessary features one by one like highlights, text formatting etc.

**Comment by navarasu** [comment]
> Good, but what about code_style?
Yes. Meaningful

**Comment by navarasu** [comment]
Today I added better screenshots for the existing dark theme in the [NEW_README ](https://github.com/navarasu/onedark.nvim/blob/readme_update/README.md). 

Next, I will work on updating the configuration section for the new config based on the above discussion.

**Comment by xeluxee** [comment]
https://github.com/navarasu/onedark.nvim/blob/c1f739280bbd8b7d6183491ca95f73195baecf83/README.md?plain=1#L7
Instead why not using `[Installation](#installation)`? This is a markdown notation, so the page isn't reloaded

**Comment by xeluxee** [comment]
> Today I added better screenshots for the existing dark themes in the [NEW_README ](https://github.com/navarasu/onedark.nvim/blob/readme_update/README.md).
> 
> Next, I will update the configuration section for the new config based on the above discussion.

Looks great!

**Comment by navarasu** [comment]
@xeluxee I am a little free this weekend. Shall I take this ticket?

**Comment by xeluxee** [comment]
I'll be available for this in two weeks or so
@navarasu sorry for the delay but in this period I'm really busy

> Shall I work on this ticket?

If you wish you can start refactoring or making light theme in the meantime
