### ISSUE TITLE
Very minor typo in README

### ISSUE THREAD

**Issue by cheeze2000** [navarasu/onedark.nvim#45]
There is a minor typo here: [Default Configuration](https://github.com/navarasu/onedark.nvim#default-configuration)
I was wondering why `comment = "none"` (under `code_style`) does not work. It turns out that it should be `comments`, I had to look at the source code to figure this one out 😂

**Comment by navarasu** [comment]
😂 . Thank you. Updated it

**Comment by cheeze2000** [comment]
Thank you, but it seems like you missed a comma at the end of the line.

**Comment by navarasu** [comment]
Done
