### ISSUE TITLE
don't enable theme at setup

### ISSUE THREAD

**Issue by quantum-booty** [navarasu/onedark.nvim#46]
I think its better to provide an api like ```onedark.load()``` rather than enable the theme at ```require('onedark').setup()```. Other colorschemes don't typically load the colorscheme at setup(), I think its best if onedark can behave similarly too.

**Comment by quantum-booty** [comment]
Also seems that the transparent = false option does not work.

**Comment by xeluxee** [comment]
Yeah we agree with you but a method as `onedark.load()` looks redundant since it should simply call `:colo onedark`

**Comment by xeluxee** [comment]
> Also seems that the transparent = false option does not work. Bottom image is using the newest commit with transparent = false.

Cannot reproduce, `trasparent` works fine for me. What terminal are you using? I'm using Kitty

**Comment by navarasu** [comment]
Same here. Cannot reproduce the `transparent` issue. Works for me in Alacritty

**Comment by navarasu** [comment]
Fixed the issue. Added new method for  enabling color scheme directly `require('onedark').load()`

**Comment by quantum-booty** [comment]
> > Also seems that the transparent = false option does not work. Bottom image is using the newest commit with transparent = false.
> 
> Cannot reproduce, `trasparent` works fine for me. What terminal are you using? I'm using Kitty

I'm using Kitty too, NVIM v0.7.0-dev+850-ge92b81633, tested on minimal init.lua
```
require('packer').startup({function()
    use 'wbthomason/packer.nvim'
    use { 'navarasu/onedark.nvim' }
end,
})


require('onedark').setup({
    sytle = 'darker',
    transparent = false,
    toggle_style_key = '<nop>',
    diagnostics = {
        darker = false,
    },
})

vim.cmd([[colorscheme onedark]])

```
