### ISSUE TITLE
How to change the style with variable?

### ISSUE THREAD

**Issue by LamprosPitsillos** [navarasu/onedark.nvim#50]
https://user-images.githubusercontent.com/61395246/148703419-7dd09a67-d2a7-47a3-b280-6f5919cf505a.mp4

**Comment by xeluxee** [comment]
Due to a Neovim bug with lua and global variables you can't directly edit fields of global dictionaries.
I'd suggest you to use `setup()` function:
``` lua
require('onedark').setup({style = 'darker'})
require('onedark').load()
```

**Comment by navarasu** [comment]
`require('onedark').setup({style = 'darker'})` - Will this update entire option or updates only `style` param?

**Comment by xeluxee** [comment]
> `require('onedark').setup({style = 'darker'})` - Will this update entire option or updates only `style` param?

It updates only `style` field because `vim.tbl_deep_extend` is used
