### ISSUE TITLE
Toggle transparent property

### ISSUE THREAD

**Issue by rod-stuchi** [navarasu/onedark.nvim#51]
Hi, first of all, thank you for this amazing theme :beer: 

I have a function to toggle transparency.
```lua
function M.toggle_transparency()
  vim.g.onedark_transparent_background = not vim.g.onedark_transparent_background
  vim.cmd[[colorscheme onedark]]
end
```
This global property`onedark_transparent_background` has present in ce49cf36dc839564e95290e2cdace396c148bca.

I tried with `require('onedark').set_options('transparent', true)` but with no success.

My question is, how can I achieve this behavior in new version?

**Comment by xeluxee** [comment]
To check option simply see `vim.g.onedark_config.transparent`

To change option use this:
``` lua
require('onedark').setup({transparent = false})
require('onedark').load()
```

**Comment by rod-stuchi** [comment]
Very nice

```lua
function M.toggle_transparency()
  require('onedark').setup({transparent = not vim.g.onedark_config.transparent})
  require('onedark').load()
end
```

Thank you so much
