### ISSUE TITLE
Should we make this default?

### ISSUE THREAD

**Issue by black-desk** [navarasu/onedark.nvim#53]
check this https://github.com/black-desk/dotfiles/commit/d122b69e3915ff8d3274773bca2cc8ee47f1e3ea

I think TSStrong should be bold :)

**Comment by xeluxee** [comment]
Yeah, why not, but what are these highlights used for?

**Comment by black-desk** [comment]
I am sure they are used for markdown.

https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/markdown/highlights.scm
