### ISSUE TITLE
Using custom colors not working

### ISSUE THREAD

**Issue by mikededo** [navarasu/onedark.nvim#57]
Hello 👋🏼 

I'm trying to customize the colorschem. However, I cannot create custom colors, as when nvim is opened, it shows: `onedark.nvim: unknown colors "<custom color name>"`.

I have also tried using the default config, given in the README, yet it does still not work:

```lua
require('onedark').setup {
  colors = {
    bright_orange = "#ff8800",    -- define a new color
    green = '#00ffaa',            -- redefine an existing color
  },
  highlights = {
    TSKeyword = {fg = '$green'},
    TSString = {fg = '$bright_orange', bg = '#00ff00', fmt = 'bold'},
    TSFunction = {fg = '#0000ff', sp = '$cyan', fmt = 'underline,italic'},
  }
}

-- It returns onedark.nvim: unknown color "bright_orange"
```

How can I solve such issue or provide anything to help debug this issue?

**Comment by xeluxee** [comment]
Hi @mikededo, I cannot reproduce your issue.
What plugin manager are you using? If using packer try to launch `:PackerCompile` after customizing colors and restart neovim

**Comment by mikededo** [comment]
I was using plug but then switched to packer, since I started using NvChad. I forgot to close the issue. My apologies 😓
