### ISSUE TITLE
Create publicly accessible palette

### ISSUE THREAD

**Issue by jonathanlamar** [navarasu/onedark.nvim#58]
It would be useful to be able to import the onedark colors for use in configs of other plugins (e.g., custom config of lualine).  I have forked the repo to add this functionality and can make a PR.

Example use case here:  https://github.com/jonathanlamar/nvim/blob/tmp/lua/colorschemes/onedark.lua#L3.  Previously, I had to manually copy the hex code.  Not a huge deal, but I think it's better to import them.

**Comment by navarasu** [comment]
Merged
