### ISSUE TITLE
Gdiffsplit colours in light style are "a bit off" ;)

### ISSUE THREAD

**Issue by wimstefan** [navarasu/onedark.nvim#61]
Thanks for that beautiful colour scheme! The `cool` style is my absolute favourite at the moment :)
The `light` is a different story though. At first sight it looks nice but if I invoke `Gdiffsplit` it's quite a difference ...
A screenshot says much more in this case I guess:
![scrot-2022-02-24-10:52](https://user-images.githubusercontent.com/4605934/155501618-8b8a36e7-0492-405d-9eee-8769cce103fa.png)

**Comment by navarasu** [comment]
Oops. Looks like I forget to update some colors. I will fix it

**Comment by xeluxee** [comment]
These colors need to be updated

https://github.com/navarasu/onedark.nvim/blob/77752edb0f8378a21f92b8a4dcad984177f24c7f/lua/onedark/palette.lua#L193-L196

**Comment by pyjamafish** [comment]
@wimstefan please try the latest master, it should be fixed now :)

**Comment by wimstefan** [comment]
> @wimstefan please try the latest master, it should be fixed now :)

It is indeed 😁
Thank you so much 🙏🏼
