### ISSUE TITLE
style option doesn't work

### ISSUE THREAD

**Issue by ravenxrz** [navarasu/onedark.nvim#66]
I changed the default theme to 'light', but it doesn't when I reopen nvim,  it always chooses the 'dark' as the default.
I can switch theme through the 'toggle style key <leadeer>ts'

![image](https://user-images.githubusercontent.com/44746032/158511210-8cc01311-f53e-4269-9710-a14008a80239.png)

Is there any way to debug/fix this?

**Comment by navarasu** [comment]
Let me check this in my local

**Comment by xeluxee** [comment]
Actually it's intended, `setup` function checks the content of `background` before setting the style
Add this before line 8: `vim.o.background='light'`

**Comment by ravenxrz** [comment]
> vim.o.background='light'

Thank you. It works now.
