### ISSUE TITLE
Is there a way to bold the single number？

### ISSUE THREAD

**Issue by cloud-mist** [navarasu/onedark.nvim#74]
Hey, this plugin is very nice. But I want to know, is there a way to only bold the number ? 
Like this picture in doomemacs.

<img src="https://user-images.githubusercontent.com/49445212/165298519-ca0546af-b9ed-43ce-9713-4308cc26a7d5.png"  width=60% />

**Comment by xeluxee** [comment]
See here: https://github.com/navarasu/onedark.nvim#customization

``` lua
require('onedark').setup {
  highlights = {
    Number = {fmt = 'bold'},
    TSNumber = {fmt = 'bold'},
  }
}
```

**Comment by cloud-mist** [comment]
@xeluxee  Thanks for your reply. It works. 🙂
