### ISSUE TITLE
Invalid configuration: Unknown function onedark#GetColors

### ISSUE THREAD

**Issue by rkabrick** [navarasu/onedark.nvim#75]
Hello... I cannot for the life of me figure out what the issue is. I know (and honestly hope) that this is an incredibly stupid error on my part. Would very much appreciate any advice you can give :) 

```
"Invalid configuration: ...site/pack/packer/start/onedark.nvim/lua/onedark/init.lua:95: Vim(let):E117: Unknown function: onedark#GetColors" file="init.lua",
```

**Comment by xeluxee** [comment]
Please tell us what neovim version are you using.
Have you tried to update `onedark.nvim`? What commit are you using?

**Comment by rkabrick** [comment]
I am on the master branch, using packer, and using NVIM v0.7.0

**Comment by xeluxee** [comment]
Can you share your config, in particular how you're calling onedark's setup function?
Also please note that we aren't using vimscript, so this error probably comes from onedark.**vim** and not from onedark.**nvim**

https://github.com/joshdick/onedark.vim/blob/7db2ed5b825a311d0f6d12694d4738cf60106dc8/autoload/onedark.vim#L27

As you can see `onedark#GetColors()` is defined there and not in `onedark.nvim`

**Comment by vasac** [comment]
I had same issue as @rkabrick - it turned on that I also had `onedark.vim` theme in `~/.vim/colors`.
