### ISSUE TITLE
about symbols...

### ISSUE THREAD

**Issue by n1rdeks** [navarasu/onedark.nvim#80]
in onedark https://github.com/joshdick/onedark.vim
all symbols, like '=' or '+-!' etc, have a color (just watch image)

maybe need add?

**Comment by xeluxee** [comment]
I agree with you, purple for operators looks better in many languages.
You can customize highlight groups:
``` lua
require('onedark').setup {
	highlights = {
		Operator = {fg = '$purple'},
		TSOperator = {fg = '$purple'},
	}
}
```
See https://github.com/navarasu/onedark.nvim#customization

**Comment by n1rdeks** [comment]
thanks.

**Comment by n1rdeks** [comment]
oops, I forgot.
