### ISSUE TITLE
support searchbox.nvim (nui.nvim)

### ISSUE THREAD

**Issue by jrafaaael** [navarasu/onedark.nvim#86]
By default, this colorscheme generate a weird highlight around [searchbox.nvim](https://github.com/VonHeikemen/searchbox.nvim). They suggested me to [use](https://github.com/MunifTanjim/nui.nvim/issues/129) `autocmd ColorScheme * highlight! link FloatBorder Normal` but generate weird highlight with others plugins. Can you check it?

**Comment by MunifTanjim** [comment]
Instead of changing `FloatBorder` globally, you can just fix it for `searchbox.nvim`. 

Just call the setup function like this:

```lua
require('searchbox').setup({
  popup = {
    -- other popup options
    border = {
      -- other popup border options
      -- do not include `highlight` here
    },
    win_options = {
      winhighlight = 'Normal:Normal,FloatBorder:Normal',
    },
  },
  -- other options
})
```

Check: https://github.com/VonHeikemen/searchbox.nvim#configuration

**Comment by jrafaaael** [comment]
Thanks! This works as expected!
