### ISSUE TITLE
Allow not setting the toggle_style_keymap

### ISSUE THREAD

**Issue by dagadbm** [navarasu/onedark.nvim#89]
Even if my configuration has:
```
  use { 'navarasu/onedark.nvim',
    config = function()
      require('onedark').setup {
        toggle_style_key = '<NOP>',
      }
    end
  }
```

if I check my mappings onedark nvim still maps this to <Leader>ts.

I do **not** want the mapping to even be set:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16737095/180471229-0b2c36b7-9983-4aa4-a185-d3b0ffba1759.png">

**Comment by itaranto** [comment]
I totally agree, a plugin shouldn't pollute the mappings unless it provides a way to disable them.

**Comment by navarasu** [comment]
You can disable the mapping like so:

```lua
require('onedark').setup {
  toggle_style_key = '<NOP>',
}
```

see `:h <NOP>`

**Comment by navarasu** [comment]
You can disable the mapping like so:

```lua
require('onedark').setup {
  toggle_style_key = '<NOP>',
}
```

see `:h <NOP>`

**Comment by navarasu** [comment]
I will change default key binging to some thing unique or will disable it will default

**Comment by itaranto** [comment]
> You can disable the mapping like so:
> 
> ```lua
> require('onedark').setup {
>   toggle_style_key = '<NOP>',
> }
> ```
> 
> see `:h <NOP>`

This works for me and I don't have any problem having a default mapping if at least I have a way to disable it.

**Comment by xeluxee** [comment]
> Even if my configuration has:
> 
> ``` lua
>   use { 'navarasu/onedark.nvim',
>     config = function()
>       require('onedark').setup {
>         toggle_style_key = '<NOP>',
>       }
>     end
>   }
> ```
> 
> if I check my mappings onedark nvim still maps this to ts.

Cannot reproduce. It works for me. Have you launched `:PackerCompile`? Often it's needed to reload configuration properly

**Comment by itaranto** [comment]
> > Even if my configuration has:
> > ```lua
> >   use { 'navarasu/onedark.nvim',
> >     config = function()
> >       require('onedark').setup {
> >         toggle_style_key = '<NOP>',
> >       }
> >     end
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if I check my mappings onedark nvim still maps this to ts.
> 
> Cannot reproduce. It works for me. Have you launched `:PackerCompile`? Often it's needed to reload configuration properly

This can happen when you run `require('onedark').load()` (or `  vim.cmd('colorscheme onedark')
` before `require('onedark').setup()`.

**Comment by Henkru** [comment]
At least for me (`NVIM v0.8.0-dev-nightly-5-g7961f7990`) with the following configuration,
```lua
require('onedark').setup({
  toggle_style_key = '<NOP>',
})
require('onedark').load()
```
`toggle_style_key = '<NOP>'` maps the `<NOP>` key sequence to the toggle function as shown in `:nmap` output,
```
n  <NOP>       * <Cmd>lua require("onedark").toggle()<CR>
```
and you are able to toggle the theme by pressing `<NOP>`. Are others able to reproduce this? Even though `<NOP>` kind of fix the problem, since you're probably not hitting that key combo, it still feels like wrong behavior to me. As @navarasu mentioned above, this should most likely be disabled by default and let the user configure it if wanted. I suggested a disable configuration option in #90 PR, but on reconsideration, disabled as a default would be the best solution.

**Comment by xeluxee** [comment]
> Even though `<NOP>` kind of fix the problem, since you're probably not hitting that key combo, it still feels like wrong behavior to me.

`<nop>` doesn't look like a combo, it's a inexistent key. See `:h <nop>`:
```
<NOP>		no-op: do nothing (useful in mappings)	*<Nop>*
```


> disabled as a default would be the best solution

Agree. If a user wants to enable it he can simply call `setup()` function to set `toggle_style_key`

**Comment by jay-ouellette** [comment]
`toggle_style_key = '<NOP>'` is adding this keymap on NVIM v0.7.2 which I think is necessary:

`n  <nop>       * <Cmd>lua require("onedark").toggle()<CR>`

How about this solution? PR https://github.com/navarasu/onedark.nvim/pull/91

Even if you're happy with `toggle_style_key = '<NOP>'`, preventing a crash when `toggle_style_key = ''` is helpful.
.
