### ISSUE TITLE
comments in python are not italicised

### ISSUE THREAD

**Issue by bastienboutonnet** [navarasu/onedark.nvim#9]
First off, super well done on the many variations!

One thing I seem to be missing is the ability to display comments (in python) in italics --a common style. Am I missing a config option? I'm not super able to understand how the code works but I do see mentions of italics so I have a feeling it's something that's maybe there.

Let me know if you need more info

**Comment by navarasu** [comment]
Sure, l will add italic support

**Comment by bastienboutonnet** [comment]
@navarasu that's awesome thanks a lot. Can't wait to see some beautiful italics from monolisa coming up <3

**Comment by luong-komorebi** [comment]
Cool, looking for italic support, too

**Comment by navarasu** [comment]
Added italic comment support and enabled it by default

#### To disable italic comment
```vim
let g:onedark_italic_comment = 0 " By default it is 1
colorscheme onedark
```

```lua
vim.g.onedark_italic_comment = false -- By default it is true
require('onedark').setup()
```

**Comment by bastienboutonnet** [comment]
Awesome @navarasu  this is so cool! I'll go ahead and update the plugin! Thanks a lot!
