### ISSUE TITLE
NvimTree picker disappears

### ISSUE THREAD

**Issue by dbarrosop** [navarasu/onedark.nvim#95]
Hello,
I started using this plugin/theme recently (which is amazing, awesome job) and noticed something strange with NvimTree. If you have multiple panes open and open a new file with NvimTree you are given the option to which pane to send it to. To make it more usable NvimTree replaces the status line of each pane with a blue line and a character you can press to choose that pane.

With this plugin the blue line replacing the statusline shows up as expected but disappears after a second or two, which isn't ideal.

Thanks!
David

**Comment by xeluxee** [comment]
Cannot reproduce. This behaviour is probably caused by another plugin

**Comment by dbarrosop** [comment]
Mmm, interestingly I can't reproduce anymore myself either. I think it might have been a bug on neovim itself as I updated it to the latest master recently. Anyway, thanks for responding and apologies for the noise.
