### ISSUE TITLE
Attempt to index a boolean value

### ISSUE THREAD

**Issue by R-Sh1ki** [navarasu/onedark.nvim#97]
Hi, everyone! 
When I use `require('onedark').load()` as the README mentioned, an error will be found:
```
Error detected while processing xxx/.config/nvim/init.lua:
E5113: Error while calling lua chunk: xxx/.config/nvim/init.lua:5: attempt to index a boolean value
Stack traceback:
        xxx/.config/nvim/init.lua:5: in main chunk
```

The line 5 in init.lua is `require('onedark').load()`. How can I solve this problem?

**Comment by R-Sh1ki** [comment]
Maybe some conflicts between onedark and other plugins. When I delete other plugins and only remain the onedark.nvim, the error is disappeared.

**Comment by navarasu** [comment]
Share me the full config to reproduce from my side

**Comment by R-Sh1ki** [comment]
> Share me the full config to reproduce from my side

Thanks for your help! I have found that `use "lunarvim/colorschemes"` contains the onedark theme, so there are two onedark theme in my nvim plugins. Now I have deleted `colorschemes`. I think this issue can be closed, I'm so sorry to trouble you.
